In [22]:
import cv2

In [48]:
img = cv2.imread('Cyberpunk-1.jpg')
img = cv2.resize(img,(432,768))
cv2.imwrite('Cyberpunk_smool.jpg',img)
img.shape

(768, 432, 3)

In [24]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [25]:
cent = []
for i in range(3):
    k = np.mean(np.mean(img,axis=0),axis=0) + np.random.uniform(-100,100,(3,))
    cent.append(k)
print(cent)

[array([224.35643848, 101.79096009, 192.1506426 ]), array([176.77912612, 151.8013046 , 132.54131603]), array([167.90815425, 124.50102765, 163.06899574])]


In [30]:
from scipy import stats
from collections import Counter

In [45]:
while(True):
    print(img[int(np.random.normal(len(img)/2,len(img)/10))][int(np.random.normal(len(img[0])/2,len(img)/10))])

[252   0   0]
[  3 255 125]
[  0 254  93]
[ 26 230   1]
[  0 224 239]
[221   2 152]
[103   0 208]
[144   0  63]
[ 22  21 229]
[157   0  90]
[  0 254 147]
[ 95 155   4]
[  1  12 255]
[  1 169 254]
[  0   2 255]
[237   9   0]
[  0 254 108]
[240  15   0]
[231  21   4]
[128   0  75]
[  4 205 255]
[  3 247 251]
[143   0 190]
[176   0  98]
[203   1  32]
[  3 227 252]
[  0 109 254]
[  1 254 239]
[ 83 169   1]
[187   0 169]
[228   0 126]
[ 43   2 231]
[246  11   0]
[194   0 166]
[252   2   1]
[  1 216 255]
[214  40   0]
[132 124   0]
[181   0 103]
[175  12 172]
[231   0 125]
[  0 239 255]
[118   0 200]
[  0 254 207]
[205   0  28]
[144   5  82]
[254   3 135]
[  0 128 253]
[136   0 194]
[162   0  58]
[132   1  72]
[  2 220 254]
[167   0  93]
[  0  86 254]
[136   0  78]
[  3  96 255]
[145   2  59]
[  0 197 254]
[180   0 101]
[177   0  97]
[  0 255  97]
[225   1 150]
[  3 253  87]
[  1  37 255]
[  1  59 254]
[  0 185 255]
[ 14 243   1]
[168   0  50]
[  0 133 255]
[184  65   0]
[ 20   2 247]
[  1 2

[  0 253 241]
[253   1 136]
[203   1  32]
[ 94 160   2]
[ 13 239   0]
[  2 255 191]
[ 95   2 201]
[  1 254  87]
[  2 255 191]
[  2 148 254]
[  2 214 254]
[141 111   1]
[159   6  89]
[  1 216 255]
[201   0  33]
[253   3   2]
[169   0  95]
[  1 252 166]
[162   4  42]
[  1 172 255]
[  2 108 255]
[  0 213 255]
[  2 226 254]
[229   0 150]
[125 128   2]
[225  31   3]
[129   2 191]
[192   1 106]
[150   9  88]
[  7   8 249]
[  0 252   1]
[204   0  29]
[  1  39 255]
[  1  43 255]
[158   2 183]
[  1 255 192]
[  1 255 254]
[162   1 181]
[255   1   1]
[114   0 202]
[  1 137 255]
[  2 119 254]
[172  80   0]
[230   1 122]
[224   0 118]
[  2 255 181]
[  0 150 255]
[204   0  32]
[167   0 178]
[  0 253 134]
[  0  82 253]
[145 112   2]
[  1 108 253]
[  1 112 255]
[  5 249   4]
[  1 254 164]
[  3 227 254]
[134   0  76]
[ 84   0 216]
[222   0  18]
[  1 254  87]
[237   0  13]
[143   0  69]
[136   0  78]
[  1   4 250]
[147   0 187]
[201   0 165]
[  0 255   6]
[246   1 142]
[191   0 169]
[101   0 211]
[  0 2

[  0 198 253]
[147   1 185]
[  0 221 255]
[  9   7 249]
[  1 253 208]
[  1 254 213]
[196   1  34]
[  1 160 255]
[  1 119 255]
[  0 255 101]
[114 141   1]
[ 71 183   2]
[178   0 100]
[  1  10 255]
[  7 255 254]
[ 59 195   1]
[  0 213 253]
[  0 128 253]
[  2 126 254]
[  0  94 254]
[149  10  92]
[245   0 144]
[ 21 217 246]
[  0 254 180]
[  2 233 253]
[ 11 242   0]
[  5   0 255]
[147  90   4]
[  1   1 240]
[  0 106 254]
[ 87   0 214]
[237   2 130]
[214   0 160]
[217   0  27]
[ 49   0 234]
[177   0 173]
[  2 210 255]
[193   1 106]
[222   0 150]
[137 122   0]
[  1  47 255]
[147   4  79]
[221   2 122]
[  4  29 255]
[ 14 245   0]
[208  44   0]
[143   1 191]
[239   1   9]
[  2 253 107]
[  0 254 218]
[158   2  89]
[  1 218 234]
[134   0  77]
[159   1  52]
[250   0   1]
[196   1 165]
[255   3 138]
[  4   0 251]
[137   0 193]
[210   2 158]
[168  85   0]
[227   0 126]
[222   0 154]
[218   0 158]
[142   0 192]
[210   2 158]
[ 61  11 214]
[164   1  56]
[235   1  12]
[  1  57 252]
[  0 248 255]
[134  

[ 81   0 218]
[138 136  15]
[252   1 139]
[  3 212 254]
[251   0   1]
[199   0 166]
[155   1  52]
[  2 202 254]
[199   0  32]
[242   0 131]
[147   4  81]
[229   0  16]
[211   0 116]
[  0 254 100]
[ 60   5 238]
[  6 109 255]
[  0 176 252]
[  1 128 255]
[167  14 100]
[  3 253 164]
[  4 255 228]
[  3 255  77]
[149  91   4]
[249   1   1]
[224   2 152]
[159   6  90]
[  4 252 251]
[104 162  11]
[116   0 200]
[  2 253 100]
[246   0   2]
[  0 254 255]
[102   0 208]
[172   0  98]
[ 34   2 241]
[  6 231 253]
[  4 252 199]
[208   1 159]
[  0 128 253]
[219   1 118]
[244   0   3]
[  3 106 255]
[  0  71 254]
[252   1 140]
[  6 222 250]
[ 14   7 249]
[  0  52 253]
[  0  48 254]
[  1 255 158]
[212   1 158]
[  4   1 254]
[196   1  33]
[  4 166 251]
[  0 153 253]
[  2 255 248]
[  0  83 254]
[  0 254  93]
[152   1 186]
[180   1 170]
[211   0  26]
[165   3  89]
[214   0 159]
[  2  64 255]
[  0 255  90]
[  2 165 254]
[177   2  42]
[230  22   0]
[ 89 164   0]
[193   1 107]
[137   0  71]
[  1 255  15]
[129 1

[  0 255 234]
[225  27   0]
[193   1  36]
[211   1 118]
[  2 240 255]
[151   0 188]
[193   0 166]
[  2 223 255]
[ 25 226   0]
[  1 255 248]
[  4 252 251]
[  2 254 247]
[  1 255  57]
[ 63 190   1]
[203   1  32]
[243   0 134]
[146   0  77]
[250   0 136]
[  4 125 255]
[107   0 205]
[  3 254 255]
[170   1  94]
[205   2  26]
[130   0 195]
[ 87 166   0]
[  0 254  10]
[125 134   0]
[150 102   4]
[208   2 158]
[250   5   1]
[131   2  67]
[  2  70 253]
[  0 218 252]
[214   0 160]
[  1 255 187]
[ 81 169   1]
[168   2  46]
[  0   3 252]
[  2 213 254]
[242   0 131]
[  1  49 254]
[  0 255 252]
[  1   5 244]
[215   0  24]
[208   1 160]
[ 37  35 255]
[  0 166 253]
[  0 186 255]
[132   1  75]
[  1 102 254]
[  1 103 252]
[242   0 133]
[229  30   5]
[  0 164 253]
[134   0  78]
[  0 161 255]
[167 137  54]
[181   0 102]
[111   0 201]
[  3 255 138]
[185 139  67]
[115   0 202]
[  0 255 230]
[  2 234 253]
[  2 255 255]
[214   0 160]
[  0 253 133]
[  0 252 251]
[  0 127 255]
[  3  37 255]
[180   0 179]
[202  

[  4 218 254]
[205   1  30]
[  2 101 254]
[ 49   3 225]
[202   0  31]
[246   0 136]
[  2  53 255]
[  5 218 247]
[208   2 158]
[146 128  30]
[216   1 158]
[195   0  32]
[148   0 191]
[  5 232 253]
[179  59 129]
[ 98 155   0]
[  1  42 254]
[133   0 194]
[  2   9 255]
[209  45   2]
[  1 255 171]
[ 14 240   3]
[  1 127 253]
[122   0 198]
[  3  98 255]
[  3 199 255]
[ 17   2 248]
[172  79   0]
[ 15 246 246]
[133   0  73]
[  0 222 254]
[207   1  26]
[  0 167 254]
[131   0  75]
[113  48 217]
[252   0   1]
[  1 252 255]
[  1 143 255]
[203   0 165]
[123 116   0]
[164   1  93]
[  0   3 246]
[209   0  28]
[  2 254 152]
[  2 214 254]
[  4 223 251]
[  2 240 255]
[  0 205 253]
[ 12 137 251]
[251   0   2]
[ 99 156   0]
[  0 117 253]
[  2 100 254]
[ 94   0 213]
[252   0   3]
[  0 123 255]
[245   8   0]
[171   1  46]
[  1 104 255]
[  3 198 255]
[160  93   5]
[  0 255 239]
[  1 255 101]
[  0  74 254]
[247   0 137]
[  0 255  19]
[  5 251  50]
[  0 154 253]
[113 141   0]
[  4  71 255]
[208   1 160]
[  3  

[  1 254 231]
[  2  16 254]
[  4   2 254]
[  0   9 252]
[201  55   0]
[  0 171 254]
[203   1  28]
[  2  70 253]
[244   8   1]
[  0 149 254]
[ 89   0 213]
[228   0 123]
[  0 134 254]
[  2 253   2]
[  0 253 192]
[252   1   0]
[  0 125 255]
[  0 139 255]
[ 53   0 230]
[160   1  93]
[  3 225 250]
[  1 254 254]
[162   2  91]
[177   1  44]
[153 122  13]
[  4 125 255]
[132 120   2]
[  0 254 253]
[157 144  34]
[207   1 113]
[  1 207 253]
[  6 253  25]
[  0  59 253]
[201   0 111]
[245   0 134]
[  2 241 254]
[  0 162 254]
[253   0   4]
[  0 255  77]
[171   0  93]
[157  98   2]
[  3  98 255]
[  0 249 255]
[122 131   1]
[  2  57 254]
[  1 126 254]
[  1 171 255]
[154  12  95]
[  1  62 255]
[  1 255  62]
[187   0 169]
[  1 254 120]
[173  80   2]
[203   1  32]
[ 23 252 232]
[  2 255   8]
[  1 254  97]
[209   0  26]
[  0 253 250]
[254   1 138]
[  1 255  51]
[  1  14 252]
[  3 139 255]
[  2 255 172]
[  1 223 253]
[94 69  0]
[  0 255 250]
[253   0   0]
[203  49   1]
[ 86   0 216]
[210   0 160]
[126   2 

[210   0 160]
[  2  97 245]
[154   0  90]
[  4 213 255]
[ 14   6 245]
[  3   1 254]
[221   2 152]
[  3   1 255]
[168  84   0]
[  5   4 255]
[  0  99 255]
[  0  25 255]
[252   1 140]
[189   0 106]
[202   0 165]
[140   0 192]

KeyboardInterrupt: 